### ISSUE TITLE
Warn the user if name:etymology:wikidata=* equals wikidata=*

### ISSUE THREAD

**Issue by Danysan1** [pietervdvn/MapComplete#1091]
Upon clicking a feature in the etymolgy map, the search box is pre-filled with the name of the feature. This is a good starting point if the user has clear how the interface and the `name:etymology:wikidata=*` tag work.
However if the clicked feature has a corresponding entity on Wikidata (that sould be tagged with `wikidata=*`, see [example](https://user-images.githubusercontent.com/8406735/193810129-d36f8bea-0bfc-4971-a265-7214eba48e60.png)) a user can misundersand what he is supposed to do and immediately select the first found item which will be the corresponding Wikidata entity.

If the element doesn't have `wikidata=*` already tagged this error results on a wrong `name:etymology:wikidata=*`. Currently I don't have any suggestion to easily prevent this case.
If instead the element has already `wikidata=*` this error results on `name:etymology:wikidata=*` having the same value of `wikidata=*`. This is clearly wrong and easily spottable before committing the changeset.

In [this GeoJSON file](https://gist.github.com/Danysan1/2d7894515d24e364e0a07de5aa0934d8) I have extracted the elements that have the value of `name:etymology:wikidata=*` equal to `wikidata=*`. Not all of these errors came through MapComplete, but some of them have, for example see changesets [115806717](https://osmcha.org/changesets/115806717/), [123866427](https://osmcha.org/changesets/123866427/), [126908692](https://osmcha.org/changesets/126908692/), [120488035](https://osmcha.org/changesets/120488035/).

I propose to prevent some of these errors from being committed by
1. checking right after the choice of `name:etymology:wikidata=*` (or right before committing the change into a changeset) whether the choosen value is equal to the value of  `wikidata=*`
2. if it is, showing a confirmation popup warning the user of what he is doing.

**Comment by pietervdvn** [comment]
This is a cool check you did there!

I did have a look to these entries.

First of all: [this one](https://www.openstreetmap.org/changeset/120488035) is basically in my backyard. There are two wrong entries out of >40 changed topologies, so I'm guessing this one is due to an honest mistake. Also: it is not possible to _erase_ an etymology; only to change it. In the case of the 'Pathoekeweg', I suspect the contributor did (wrongly) select the entity itself; didn't find the corresponding wikidata-item for 'Pathoeke' (as there wasn't one back then) and just ignored it. 

The other three are small changesets (max 2 changed entities each), but 100% wrong.

Second, I'm really surprised that the contributors making these errors are long-standing contributors with >1k changesets each. I could understand a newbie making this error, but this is weird.

Quite often, this kind of error can be fixed by _improving the wording of the question_. I checked the 'locale'-tag of the linked changesets: 2 en, 1 de, 1 nl. However, I do think wording is fine.

At last: seen the very small amount of errors (< 10) made (over [85000](https://mapcomplete.osm.be/?mode=statistics&filter-theme-search=%7B%22search%22%3A%22etymology%22%7D&filter-theme-search-search=etymology) entities have been changed with the etymology theme!), I'm not extremely worried about this.
