### ISSUE TITLE
Issue with mph svg links on the maxspeed map

### ISSUE THREAD

**Issue by trivisonno** [pietervdvn/MapComplete#1095]
I think L119 at 'https://github.com/pietervdvn/MapComplete/blob/develop/assets/layers/maxspeed/maxspeed.json' is causing broken images.

The map is trying to create an icon using 'https://mapcomplete.osm.be/assets/themes/maxspeed/maxspeed_50%20mph%20mph.svg' (adds an extra ' mph'). 

I think we should change L119 from
`"then": "./assets/themes/maxspeed/maxspeed_{maxspeed} mph.svg"`
to
`"then": "./assets/themes/maxspeed/maxspeed_{maxspeed}.svg"`

The OSM {maxspeed} key values should already have the ' mph' following the numeric speed limit.

![image](https://user-images.githubusercontent.com/9049184/194722071-1a7e5fcc-d908-426f-8ae0-3ed775e4f252.png)

**Comment by pietervdvn** [comment]
Fixed in d562e7fd7.

This is actually a pretty interesting bug: "50 mph" is _not_ supposed to match the rule `maxspeed~[1-9]0|1[0-4]0` but the block below.

Regexes are supposed to express the _entire_ content, e.g. to avoid `access~no|private` to match `access=snowmobile` (`no` is contained in sNOwmobile).

As a result, the parser would add `^` and `$` to the regex, resulting in `^private|no$` (which won't match snowmobile).

However, due to the precedence rules of regexes, `^private|no$` is equivalent to `(^private)|(no$)`. In other words, `access=private_jet` _would_ match. `access~private|no|customers` will be interpreted as `(^private)|no|(customers$)`, thus it would match `snowmobile`...

The solution is to parse a value as `^(value)$` instead of `^value$`.
