### ISSUE TITLE
onwheels / parking_space=disabled missing

### ISSUE THREAD

**Issue by JLZIMMERMANN** [pietervdvn/MapComplete#1189]
**FACT** : the map for wheelchairs is very interesting : it displays parkings (saying if it has places for disabled), crossings, kerbs, shops and doors 
![image](https://user-images.githubusercontent.com/4929752/209439202-42c21a47-380b-478b-9b67-c7bfc4be7465.png)

**WAITED** : if we wish to let understand the whole path taken for someone using a wheelchair we need to display disabled parking space
![image](https://user-images.githubusercontent.com/4929752/209439323-8bfb38fa-0fe5-49d2-9a3f-fd9f00f3497c.png)

**Comment by JLZIMMERMANN** [comment]
Well done : the pictogram is missing ;-)
![image](https://user-images.githubusercontent.com/4929752/209527001-c1d2d26d-21a5-4df4-bcf7-35f446d91e0b.png)

**Comment by RobinLinde** [comment]
I explicitly chose to not add it, since I think the icon for parking space is more important, and an iconbadge would be tiny. Though I now have opened a PR (#1196) for an alternative rendering with wheelchair icon. ![new parking space rendering](https://user-images.githubusercontent.com/1395345/209569726-714876b7-7f08-47ec-be42-9fe42f40474f.png)

**Comment by JLZIMMERMANN** [comment]
Thank you for all you all are doing. All those maps are so well improved. 
Well done 🤩
