### ISSUE TITLE
Add OpenStreetMap Americana as background option

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1204]
If possible, add [OpenStreetMap Americana](https://github.com/ZeLonewolf/openstreetmap-americana) as background option.

**Comment by RobinLinde** [comment]
Also related to #407/#1182

**Comment by pietervdvn** [comment]
@danieldegroot2 As vector tile support is finally implemented, could you please post details about the API endpoint for the vector tiles?

**Comment by ZeLonewolf** [comment]
We would be happy to have Americana be a background option in MapComplete.
Here are the details you'll need for the base map:
TileJSON: https://tile.ourmap.us/data/v3.json
StyleJSON: https://zelonewolf.github.io/openstreetmap-americana/style.json
Fonts: https://zelonewolf.github.io/openstreetmap-americana/fonts/{fontstack}/{range}.pbf

In order to render the shields, we are not quite there yet.  We only recently published the [highway shield generator](https://www.npmjs.com/package/@americana/maplibre-shield-generator) as an npm package, however, I don't have a good example written up yet that I can easily hand off. This work is ongoing and documented in ZeLonewolf/openstreetmap-americana#70.

Note that we are also in the process of reorganizing our repository and I expect the font location to change in the near future.

**Comment by thibaultmol** [comment]
@ZeLonewolf have you considered making an issue on
https://github.com/osmlab/editor-layer-index
To have it be included in the default tile index (I'm afraid they might not accept it. But who knows).
If they do accept it, it'll automatically be added to mapcomplete as well

**Comment by ZeLonewolf** [comment]
@thibaultmol I think we are not quite there yet because of the ongoing work to make the style readily deployable and the likelihood that URLs will change as we mature the various components. However, if folks want to experiment with it, I welcome it.

**Comment by pietervdvn** [comment]
![image](https://github.com/pietervdvn/MapComplete/assets/1466478/d605e176-44e9-4687-bc42-9b7cb93364b3)

**Comment by pietervdvn** [comment]
Will be online on the test version in about an hour: https://pietervdvn.github.io/mc/develop

(You still need to switch the background layer with the bottom-left button)

**Comment by ZeLonewolf** [comment]
It looks good!  Shields and icons do not render as expected, but the base map appears to work normally.
