### ISSUE TITLE
List of all apps/themes

### ISSUE THREAD

**Issue by ToastHawaii** [pietervdvn/MapComplete#122]
Are you willing to give me a complete list of all apps/themes that MapComplete provides? 

I working on a website (https://osm-apps.zottelig.ch/) that lists all OSM based apps. I crawl the osm wiki and collect all apps infos that are document with «[Software](https://wiki.openstreetmap.org/wiki/Template:Software)» or «[Service item](https://wiki.openstreetmap.org/wiki/Template:Service_item)» (https://wiki.openstreetmap.org/wiki/List_of_OSM-based_services) template.

Or maybe you have the time and motivation to document them by yourself into the osm wiki eg. with an own wiki page about MapComplete (https://wiki.openstreetmap.org/wiki/MapComplete) and a full list of all themes?

**Comment by pietervdvn** [comment]
Hey ToastHawaii,

I can give you a _partial_ yes on that.

All* the official themes are .json-presets that can be found [here](https://github.com/pietervdvn/MapComplete/tree/master/assets/themes) - where a them is a collection of layers. The idea is that a theme is relevant for a certain interest (e.g. cycling, or nature lovers, or climbers, ...). Some specific layers are for a single theme, some layers are reused and can be found [here](https://github.com/pietervdvn/MapComplete/tree/master/assets/layers). These builtin-themes can also be found in the 'more'-tabpage in MapComplete itself.

(*): there are still a few themes defined in the code, but I'm converting those into a json-preset step-by-step.

However, people are able to create their own themes. These themes are saved in the URL and can not be accessed by me. To work around this issue, I'm adding the possibility to load a theme from the OSM-wiki - basically one can put a JSON-file on the wiki which'll be loaded if MapComplete gets pointed to it.

For those custom themes, I cannot give you a list of themes, because I hope that there'll be new themes popping up constantly one day.

> Or maybe you have the time and motivation to document them by yourself into the osm wiki eg. with an own wiki page about MapComplete (https://wiki.openstreetmap.org/wiki/MapComplete) and a full list of all themes?

Sure, is there a certain wiki-template I have to use to get picked up by your application automatically?

**Comment by ToastHawaii** [comment]
> Sure, is there a certain wiki-template I have to use to get picked up by your application automatically?

No you can create a normal page and use one or many [Software Template](https://wiki.openstreetmap.org/wiki/Template:Software) (Service Item Template or Layer Template) inside it to describe MapComplete and the themes. The App will find them.

E.g.:
```
{{Software
|name           = xyz
|author         = 
|wiki           = xyz
|web            = http://www.xyz.org
|repo           = http://
|platform       = web
|code           = Typescript;HTML;CSS
|languages      = DE;EN;MUL
|genre          = display;editor
|screenshot     = xyz.jpg
|description    = Easy to use, nice UI
|map        = yes
|findLocation            = yes
|findNearbyPOI           = yes
|addPOI          = yes
|editPOI         = yes
|editTags        = yes
|
}}
```

I already document some of them with the other template (Service Item) the application understands:
https://wiki.openstreetmap.org/wiki/List_of_OSM-based_services
(The App supports auto merge from double entries.)

But I think it's better if MapComplete has its own Wiki page. That makes it easier to add new themes.

**Comment by pietervdvn** [comment]
Allright, [here you go](https://wiki.openstreetmap.org/wiki/MapComplete)

Is there a way to link to external pages for the screenshots?

**Comment by ToastHawaii** [comment]
> Is there a way to link to external pages for the screenshots?

I guess the Wiki does not allow this...

**Comment by pietervdvn** [comment]
Okay, then the screenshots will stay the generic 'bookcase-map' screenshots for now.
