### ISSUE TITLE
AGIV imagery: no z 21

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1252]
Just noticed that if you zoom in to level 21, and are using the recent imagery from the Flanders gov (AGIV), you get a 400 error from the WMTS server.  EDIT: solution is to not have the imagery go to zoom level 21, but still allow mapcomplete to zoom to 21 (just show z 20 of the imagery layer instead)

[Screen recording 2023-01-14 11.58.10.webm](https://user-images.githubusercontent.com/1010226/212469040-77b1503b-be33-4e06-9bbc-4855729615cb.webm)

![image](https://user-images.githubusercontent.com/1010226/212469048-9ea22605-2dc8-4ad6-acc0-47eeb6df39b6.png)

I am using the beta version of chrome but don't think it's related
https://www.whatsmybrowser.org/b/W5SWB

**Comment by pietervdvn** [comment]
Sorry, but I cannot reproduce this issue.

For me, the tiles are loading just fine. Example of a tile at zoom level 21: https://tile.informatievlaanderen.be/ws/raadpleegdiensten/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=omwrgbmrvl&STYLE=&FORMAT=image/png&tileMatrixSet=GoogleMapsVL&tileMatrix=21&tileRow=700079&tileCol=1067331

It might be that tiles are not available _in your region_. Can you share a link?

In either case, I'm reusing the Editor Layer Index, so if this turns out to be a bug, it has to be handled at https://github.com/osmlab/editor-layer-index

**Comment by thibaultmol** [comment]
WEIRD. should have rebooted my chromebook just as a test. it's a beta version of Chrome/chromeos but still yeah.
It's not happening anymore... :man_shrugging:
