### ISSUE TITLE
FR: Simple changelog

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1277]
I realized something that StreetComplete does which MapComplete doesn't (Not that it should have feature parity.)
But something cool that they do: show what changed in the new version. Like a changelog, but inside the app itself

**Comment by pietervdvn** [comment]
The reason that this isn't included is mainly because I then have to keep track of what features I added. I often add features when I feel like it and I deploy when I feel it's the right time to deploy. (That's mostly when develop is somewhat stable and some bugs in production are fixed in it)

It is true that communicating better about new features might help adoption of those new features. Right now, I sometimes do this via Mastodon, but of course, many contributors don't follow MapComplete on Mastodon.

On the other hand, for new and non-technical users, such an extra popup can be confusing and break their flow.

At last, I try to not make big changes in the UI so that regular contributors (myself included!) can grow together with the UI and are not presented with big changes at once.

**Comment by pietervdvn** [comment]
Another thing: I try to let features appear when they are needed and useful - for example by reading the number of changesets. This means that features gradually appear: a contributor 'levelling up' will suddenly see the tags that are added or will suddenly gain access to e.g. the custom theme generator.

In the same vein, the 'level selector' (the little elevator) will only appear if there are features on multiple levels, or some niche questions will only appear if relevant for the POI.

**Comment by tordans** [comment]
Maybe looking at it this way helps to come to terms with the additional effort to have a changelog: It is good marketing. It allows to communicate version updates and their features easily which creates buzz for the project again and again.

There are workflows that make it easier to generate changelogs semi-automatically, if this is something that helps. However, they all require a certain level of structure :-).

**Comment by riQQ** [comment]
One option is https://www.conventionalcommits.org/.

**Comment by pietervdvn** [comment]
Since a while, the changelogs are being created, so this issue can be closed.
