### ISSUE TITLE
Add service:bicycle:diy etc. to cyclofix

### ISSUE THREAD

**Issue by maphouse** [pietervdvn/MapComplete#1387]
Several distinctions re bike repair services would be much appreciated in cyclofix. Currently, there are black icons for repair shops and red for retail. It would be great to also have the following distinctions as well:
1. [service:bicycle:diy](https://wiki.openstreetmap.org/wiki/Key:service:bicycle:diy)
2. [service:bicycle:second_hand](https://wiki.openstreetmap.org/wiki/Key:service:bicycle:second_hand)
3. and possibly even [service:bicycle:ebike_maintenance](https://wiki.openstreetmap.org/w/index.php?title=Key:service:bicycle:ebike_maintenance&action=edit&redlink=1 "Key:service:bicycle:ebike maintenance (page does not exist)") since demand is on the rise

Some other mapcomplete themes have subcategories as seen below:
![image](https://user-images.githubusercontent.com/4475249/233814042-15e37dee-cb8e-4eb8-b10b-452b1bc95261.png)

This kind of legend organization might help for applying these suggested changes in [cyclofix](https://mapcomplete.osm.be/cyclofix.html)

**Comment by pietervdvn** [comment]
Hi there,

As I explained in the email, I'm currently not actively fixing those issues. However, another maintainer might step in or you can add those filters yourself via a pull request which I'll hapilly merge.

I'd also like to point out that `service:bicycle:ebike_maintainence` is _not_ asked in the form when clicking a bike shop. This too can be added. For example, [the question if bike repair is offered is here](https://github.com/pietervdvn/MapComplete/blob/develop/assets/layers/bike_shop/bike_shop.json#L362) - you can copy/paste this section and modify it for ebike-maintanence.

**Comment by brunnerpaul** [comment]
I've now filed a pull request for `service:bicycle:diy` and `service:bicycle:second_hand`, would be great to see those in Cyclofix!

Looking at taginfo, I'm not sure about the addition of service:bicycle:ebike_maintenance: 
- [23 uses](https://taginfo.openstreetmap.org/keys/service%3Abicycle%3Aebike_maintenance) of service:bicycle:ebike_maintenance
- [19 uses](https://taginfo.openstreetmap.org/keys/service%3Abicycle%3Aebike_service) of service:bicycle:ebike_service

As of now, neither has a wiki entry and I feel like "maintenance" gets misspelled often, so maybe we'll end up with service:bicycle:ebike_repair? `repair` as part of a tag also is more common: https://taginfo.openstreetmap.org/search?q=repair#keys

I'm also assuming that one has to go to the place where one bought the bike (because of specific brands, special parts, software etc.), long story short: might need a clear tag and wiki entries to make better use of it before we add it IMHO.

**Comment by brunnerpaul** [comment]
I've made a PR for some translation adjustments, including changing "second hand" to "second-hand" for the new filters.
Otherwise I think it all looks good?

@maphouse, another point about repair of ebikes: The current wiki entry for [shop=bicycle](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dbicycle) also lists this:

key | possible values | description
-- | -- | --
service:bicycle:ebike | yes/no | Electric bicycles are sold **and generally serviced** here.

So adding the extra tag for ebike repair would only be needed for those stores that repair but don't _sell_ ebikes. 

I guess ebikes are a bit more like cars when it comes to repair, meaning the electric parts and the motor can't just be serviced by any mechanic and you might just have to take it to the shop where you bought it. But I'll ask around in the bike shops, have to do some surveys now for the second-hand and DIY tags. :)

**Comment by maphouse** [comment]
> I've made a PR for some translation adjustments, including changing "second hand" to "second-hand" for the new filters. Otherwise I think it all looks good?
> 
> @maphouse, another point about repair of ebikes: The current wiki entry for [shop=bicycle](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dbicycle) also lists this:
> key 	possible values 	description
> service:bicycle:ebike 	yes/no 	Electric bicycles are sold **and generally serviced** here.
> 
> So adding the extra tag for ebike repair would only be needed for those stores that repair but don't _sell_ ebikes.
> 
> I guess ebikes are a bit more like cars when it comes to repair, meaning the electric parts and the motor can't just be serviced by any mechanic and you might just have to take it to the shop where you bought it. But I'll ask around in the bike shops, have to do some surveys now for the second-hand and DIY tags. :)

looking grrreeat
![image](https://user-images.githubusercontent.com/4475249/235480160-76d9995e-8942-4214-a845-d7e47b80daa9.png)

**Comment by maphouse** [comment]
> I've made a PR for some translation adjustments, including changing "second hand" to "second-hand" for the new filters. Otherwise I think it all looks good?
> 
> @maphouse, another point about repair of ebikes: The current wiki entry for [shop=bicycle](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dbicycle) also lists this:
> key 	possible values 	description
> service:bicycle:ebike 	yes/no 	Electric bicycles are sold **and generally serviced** here.
> 
> So adding the extra tag for ebike repair would only be needed for those stores that repair but don't _sell_ ebikes.
> 
> I guess ebikes are a bit more like cars when it comes to repair, meaning the electric parts and the motor can't just be serviced by any mechanic and you might just have to take it to the shop where you bought it. But I'll ask around in the bike shops, have to do some surveys now for the second-hand and DIY tags. :)

Same re surveying! This is awesome. Hopefully ebike repairs don't go that route tho...!

**Comment by maphouse** [comment]
Hey guys, I noticed the filters @brunnerpaul proposed were no longer in the latest vector-basemap version of cyclofix. I hope they (or some variant) of them will return soon!

**Comment by pietervdvn** [comment]
@maphouse Can you check again? 

I'm seeing them as they should be: 
![image](https://github.com/pietervdvn/MapComplete/assets/1466478/187df302-5d1a-4650-9f32-50d30efb675d)
