### ISSUE TITLE
Can't find all buildings that are not specific buildings

### ISSUE THREAD

**Issue by openbrian** [pietervdvn/MapComplete#1401]
I'm trying to build a query that will categorize unknown buildings.  I set my overpassTags like this

        "and": [
          "building=yes",
          "building!~government|office"
        ]

I'm getting "Not a valid (LZ-compressed) JSON".

Maybe related to #1075.  With developer tools in the browser, I'm not seeing the pipe in the regex match.

Note: https://mapcomplete.osm.be links to https://pietervdvn.github.io/mc/legacy/070/customGenerator.html  Not sure if this is intended.

If we can get this working, I intend to build a building categorizer, using rules similar to here https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/building_type/AddBuildingType.kt#L15

**Comment by pietervdvn** [comment]
Hi,

Does it work in the custom theme generator (which is quite old)?

The problem here is that the JSON-file (which encodes your custom map) gets encoded and sideloaded via the URL as `https://mapcomplete.osm.be/theme.html?userlayout=true#<encoded json file>`.

If there is a bug with your file, it'll crash.

Can you upload your json-file in this issue? Alternatively, feel free to join [the matrix chat channel](https://app.element.io/#/room/#MapComplete:matrix.org) for more help.

**Comment by openbrian** [comment]
I'll try to upload the data soon.

**Comment by pietervdvn** [comment]
Please, give this another try using https://mapcomplete.org/studio
