### ISSUE TITLE
Theme suggestion: things with image tags

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1499]
It would be nice if there was a theme included with the default Mapcomplete that shows all nodes/ways with image tags on them. Just to see what visuals are available in the area.

**Comment by pietervdvn** [comment]
The [open image map](https://mapcomplete.osm.be/theme.html?z=18&lat=51.2132&lon=3.217941&userlayout=https%3A%2F%2Fraw.githubusercontent.com%2Fseppesantens%2FMapComplete-Themes%2Fmain%2FOpenImageMap%2FOpenImageMap.json&layer-range=false) was actually one of the first custom themes that were ever created.


However, I will *not* pull in this theme within the official MapComplete, due to inherent usability problems. Someone who is not used to OSM, 

1. will wonder why some objects do have images and others have not;
2. will want to add new images to objects...
3. ...or want to add new objects of a random category.

As such a map is not about a certain category of things (but rather about random stuff that happens to have an image), it is also very hard to pinpoint a group of people who might be interested in this (apart from "curious OpenStreetMap-people).


So, to wrap it up: this map does not fit within the vision of the official MapComplete (but I'm very happy with it and love that it exists as unofficial theme)

**Comment by thibaultmol** [comment]
> 2. will want to add new images to objects...

Is there a problem with that, though?
That was my mindset when wanting this theme. Because I wanted to see which things didn't have images yet.

**Comment by pietervdvn** [comment]
Also see https://www.openstreetmap.org/user/Pieter%20Vander%20Vennet/diary/405598#comment58544

**Comment by pietervdvn** [comment]
> Is there a problem with that, though?

To answer this question about a year later: yes, there is a problem with this if a user wants to add a picture to an object that doesn't yet have a picture: it will not be shown on the map and, as such, the user will not be able to add a picture!

**Comment by thibaultmol** [comment]
> To answer this question about a year later: yes, there is a problem with this if a user wants to add a picture to an object that doesn't yet have a picture: it will not be shown on the map and, as such, the user will not be able to add a picture!

oh yeah no, I fully agree, it'd love to use a theme like to just walk around and take pictures. Think i wrote that wrongly somehow before.

either way: is this issue going to be opened again then? or a new one created?

**Comment by pietervdvn** [comment]
Nope! As outlined above, this cannot be made user-friendly as outlined above.

(I've stumbled upon this issue again because binette created a similar theme)

**Comment by Binnette** [comment]
Hum, if maybe we can show all the "POI that can benefits to have a image". Then we put a green icon for "POI with image" and a red icon for "POI without image". But I don't know if it is possible with themes filters, etc.
