### ISSUE TITLE
Ghost bike icon shouldn't have a Christian cross

### ISSUE THREAD

**Issue by b-jazz** [pietervdvn/MapComplete#163]
Ghost bikes are not specific to memorializing a rider of a single religion, therefore the marker icon* shouldn't have a Christian cross included above the bike.

* assets/layers/ghost_bike/ghost_bike.svg

**Comment by pietervdvn** [comment]
Hey B-Jazz,

It seems that you're upset because the cross is associated with the christian religion and that you'd thus like to keep the theme neutral.

In the western culture, this cross however also has the meaning to indicate as tombstone. The icon should convey the meaning that "someone passed away" and "it is related to bicycles". The combination of the cross and the bicycle does this quite well; especially given the very tight space constrains. 

At last, this has become a bit of a hobby project (the original funding has dried up). If you happen to have some design skills or know a designer that can make a better icon, I would be happy to merge a pull request proposing a different icon. Until a better one is proposed, the current one seems to be suitable.
