### ISSUE TITLE
Question: What are the criteria for something to show up on the Cafes and pubs map?

### ISSUE THREAD

**Issue by RayBB** [pietervdvn/MapComplete#1703]
Does it have to be `amenity=cafe` or could it work to just have `cuisine=coffee_shop`?

I ask because there are some places that are tagged as restaurants (I assume because they have full menus) but actually have a more cafe vibe where you could go and sit and read and just have a small drink.

**Comment by pietervdvn** [comment]
Hi,

You can see all this information in the automatically generated documentation. For [cafes and pubs, it is here](https://github.com/pietervdvn/MapComplete/blob/master/Docs/Layers/cafe_pub.md#basic-tags-for-this-layer).

_This was generated incorrectly till just now, but it does show the tags and an overpass link now_

**Comment by pietervdvn** [comment]
It has to be `amenity=cafe` to show up in the [cafes and pubs](https://mapcomplete.org/cafes_and_pubs) map. Otherwise, the thematic map [food](https://mapcomplete.org/food) might be used.

I'm open to also include different tags in either layer, but I have to admit that some places really are in the gray area between a pub/cafe and a restaurant, so maybe we should figure out a way to properly tag this.

**Comment by RayBB** [comment]
@pietervdvn  Thanks for updating the docs!

A bit of feedback:
It says
> Elements must have the all of following tags to be shown on this layer:
> [amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=[bar](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbar) |[amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=[pub](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpub) |[amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=[cafe](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcafe) |[amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=[biergarten](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbiergarten) |[amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=[nightclub](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dnightclub)

I can interpret this as the `|` being an `OR` then this kinda makes sense. I think this is what is meant.
But the phrase `Elements must have the all of following tags` is kinda confusing. I assume this is because there would normally be more than one bullet point in the list but there just isn't for this particular case.

Not sure what the better phrasing is. Though.

# Tagging

On the note of how to deal with tags, I really am not that connected to the tagging discourse on OSM so I don't have any opinion. However, since moving to Europe I'll say that the distinction between them is extremely blurry. In my particular case I want to find places that I can work from. Which means they are fine with me ordering one drink and sitting there for a while with a book or laptop. Loosely, to my mind a place is a restaurant if you can order a full hot meal there. So in that case something can be a restaurant and also have that `coffee_shop` vibe that is fine with you working from there. Not sure how this translates into OSM tagging world though.

BTW thanks for all the great work you do on this project it is so awesome :)

**Comment by pietervdvn** [comment]
> I can interpret this as the | being an OR then this kinda makes sense. I think this is what is meant.
But the phrase Elements must have the all of following tags is kinda confusing. I assume this is because there would normally be more than one bullet point in the list but there just isn't for this particular case.

Good catch, I'm changing this.



Yeah, the range between pubs and restaurants is blurry, from places where one can only drink, to places which sell e.g. some crisps or cheese as side dish, to places which serve croques up till places that act like a restaurant during certain hours and pubs at other hours...

I don't have good tagging to capture all the nuances right now...
