### ISSUE TITLE
Don't use image:0 as it breaks compatibility with other apps

### ISSUE THREAD

**Issue by Zaczero** [pietervdvn/MapComplete#1753]
Hello! I have recently noticed that MapComplete creates objects with the image:0 tag. I understand that the idea is to allow for image galleries (where subsequent images have :1, :2 etc.). However, the most important thing about OpenStreetMap is interoperability. It's very important that other applications can use the data we produce. I strongly recommend that MC switches to using "image" tag for the first, default image (implicit :0). If we stick to that logic, one may start mapping objects like name:0, highway:0, which would be quite a bad idea :smile:.

Example object:
https://www.openstreetmap.org/node/7733982627/history

**Comment by thibaultmol** [comment]
I think this might be a bug honestly, it used to just do image= if there's only one image.

**Comment by thibaultmol** [comment]
Atleast a month ago it would add the first image as `image` and then the second as `image:1'
![image](https://github.com/pietervdvn/MapComplete/assets/1010226/40a70265-8956-46a4-91eb-1f77aa50b6f4)

**Comment by thibaultmol** [comment]
oh wait no, I think it was that the first image is normally `image=` and then the second image is `image:0=`

**Comment by Zaczero** [comment]
Closing as it most likely is no longer an issue.

**Comment by pietervdvn** [comment]
Normally, 'image' is used as first tag. However, if a contributor adds two images and then deletes the first image, the 'image' tag might dissappear and only'image:1' might remain.


Also: don't tag for the renderer. Other applications should implement 'image:n'. If one was only allowed to use tags that all other applications know if, there wouldn't be many tags in use. Seehttps://wiki.openstreetmap.org/wiki/Any_tags_you_like 

So, instead, go and complain with the apps that cannot deal with this scheme so that they implement it as well.

At last, values can onlu be 255 characters long - so using multiple tags is the only straightforward technical solution

**Comment by thibaultmol** [comment]
I can't seem to replicate it atleast. If I add one image: it adds it as `image`. if I add two images then it adds a `image`and a `image:0`

Went to look for nodes in Belgium atleast that have image:0 but no image tag and seeing which of those were caused by mapcomplete.

It seems like there are a hundred or so. Most of them caused by mapcomplete 3 years ago when there was problably a bug.

Did find this from a year ago:
![image](https://github.com/pietervdvn/MapComplete/assets/1010226/3b2a6311-c4ba-44b4-8ed9-d62e11abc3ab)
What seemed to have happened here is: node had an image, user uploads new image and deletes the original. So then you get left with an image:0
@pietervdvn would you consider this something that needs to be fixed? Basically:

> If the `image` tag on an object gets deleted by the user and in the same session uploads a new image to the object, that image should get the `image` tag instead of `image:0`
