### ISSUE TITLE
Support image:license tag

### ISSUE THREAD

**Issue by Zaczero** [pietervdvn/MapComplete#1754]
It would be nice for MC to automatically set image:license tag during photo upload.

**Comment by thibaultmol** [comment]
(Pieter is free to correct me) but the idea was that this would massively clutter up the osm database. Imagine if a place has 5 images then it would have 10 tags because each file needs it's license.
The idea is that (similar to an image on Wikimedia Commons) that the image license is listed there.
Currently with Imgur this is not easy to query, which Pieter is aware of, but all the licenses of mapcomplete uploaded images are available in a file plus the plan is to move to a different solution in the future, see: https://github.com/pietervdvn/MapComplete/issues/1451

**Comment by Zaczero** [comment]
I personally wouldn't worry much about "cluttering up" when it comes to providing license information to images. I think the focus should be on usability for data consumers. Please see that section: https://wiki.openstreetmap.org/wiki/Key:image?uselang=en#...with_the_best_license?. Currently a big issue for data consumers is difficult/unclear image license information and such a simple fix would result in a big usability boost. Without it, we "clutter up" database with image links that many applications can't simply use.

**Comment by pietervdvn** [comment]
No.

What license an image has is *not* an inherit property of the object we tag. Second, if the author changes to a more permissive license, they'd have to update the database all over. Anf what with images that stay online in some repository, but the corresponding OSM-object has been removed? The license information will have vanished as well. 

And at least, what if some other party (accidentially) changes the license?

And as a next step, should we then also add information about the author, the camera model, the camera settings into OSM? What if the author changes their (nick)name?

I understand where one comes from and what need it fullfills, but this is a strong no. (Aka: I will even refuse a pull request implementing this)

The better solution for this is to create a software library that knows the various locations and how to fetch licenses from them.

**Comment by Zaczero** [comment]
I see your point. Let me address your points. At the end of the day you are the one making the final decision and I respect that :slightly_smiling_face:.

> What license an image has is not an inherit property of the object we tag.

There are other tags in osm which are not inherit property, and yet they find lots of use. The best example would be source and all of its variations.

> Second, if the author changes to a more permissive license, they'd have to update the database all over.

Yes, but *most* people won't do that. It's a relatively rare scenario.

> And what with images that stay online in some repository, but the corresponding OSM-object has been removed? The license information will have vanished as well.
> And at least, what if some other party (accidentially) changes the license?

The information is contained within the specific object version which is never removed. I believe this situation is quite implementation-specific as each website can handle such situation differently. If I were to host images publicly, I would simply store a copy of license information alongside the image file on disk. If author decides to update the license, I would simply push change to both the disk storage and osm database.

> And as a next step, should we then also add information about the author, the camera model, the camera settings into OSM? What if the author changes their (nick)name?

It's standard to include such information in EXIF metadata so I suppose there is no need for that. Many tools "just work" with that.

> The better solution for this is to create a software library that knows the various locations and how to fetch licenses from them.

That would be an ideal situation. But I personally vouch for easy of use and east of implementation. Each new library is yet another barrier to utilize the full OSM data. image:license, while not ideal, is very easy to work with and super flexible.

**Comment by pietervdvn** [comment]
> The best example would be source and all of its variations.

Which is a tag that should go on the changeset. Consider that the first version of some POI is added with Bing and `source=bing` is added (as was the custom in the beginning of OSM), then the location improved with recent aerial imagery (with iD) and the metadata is improved using Mapillary (with MapComplete). The latter two tools won't automatically update the source-tag.

As such, I always remove the (generic) `source` tag.

Second, the `source` tag still reflects some meta-information about the POI itself; whereas `image:license` is metadata about metadata of the POI.

> Yes, but most people won't do that. It's a relatively rare scenario. If that happens, database updates are relatively quick and 10,000 changes can be done in a matter of seconds.

A matter of seconds for the computer. But the human still needs to prepare and download the data and have experience with the relevant tools, making this a job of ~1hour human time.

Also: what if they link into e.g. wikimedia commons? Are we gonna duplicate those licenses too? What if someone changes their license their, but does not update OSM?

> The information is contained within the specific object version which is never removed.

Not if the data is redacted by the DWG. (OK, I admit, this is an edge case)

> . If I were to host images publicly, I would simply store a copy of license information alongside the image file on disk. If author decides to update the license, I would simply push change to both the disk storage and osm database.

This is a bigger problem: what if the picture is used in: OSM, mapillary, geovisio and Wikimedia Commons? Then the info has to be updated _everywhere_. People will definitively forget one place.

> That would be an ideal situation. But I personally vouch for easy of use and implementation. Each new library is yet another barrier to utilize the full OSM data

First of all, images are technically _not_ a part of OSM. Second, you are making it _way_ harder for data contributors to contribute images and this makes tooling way harder. Please, read about database normalisation.

Furthermore, it isn't the task of OSM to make 'tooling' and to make 'tooling as usable as possible'. I'm not paid by the OSMF either, I'm paid by NLNet who sees the value of simpler tools.

---

In any case, I don't think you'll be able to convince me to add an `image:license` tag, especially because your main argument and reason boils down to "it would make my usecase easier" (which I don't doubt), even though it will make maintaining the OSM-database ten times harder.

**Comment by Zaczero** [comment]
Thank you for the response! Now that I tried to convince you, I can leave in peace 😃. Great app btw!
