### ISSUE TITLE
Settings: Show changeset count for MapComplete specifically

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1833]
**Observed**
Settings shows statistic for total OSM changeset count

**Expected**
Shows (also) changeset count specific to MapComplete (query created_by or similar if possible)

(MapComplete);
![image](https://github.com/pietervdvn/MapComplete/assets/67521919/ec8e1915-5f59-4d72-8517-92e8dc19df89)

(OSM);
![image](https://github.com/pietervdvn/MapComplete/assets/67521919/ee013c04-9d8a-438f-be87-a38bc77eb74d)

**Comment by pietervdvn** [comment]
This is technically quite hard. OpenStreetMap reports the total number of changesets, but doesn't report a breakdown in editor (or editor version).

To achieve this, I'd either have to integrate another API (such as OsmCha or hdyc.neis-one.org) _or_ MapComplete would have to place a count onto every changeset (as iD does).

I'm now even wondering if showing this count is a good idea, because I'm hiding the concept of 'changeset' completely on all other places of MapComplete...

In either case: it is only included because it is quite easy to do. However, I'm not interested in showing a more advanced breakdown and won't even merge a pull request for this.

**Comment by pietervdvn** [comment]
(If you are interested in the breakdown, please use hdyc: https://hdyc.neis-one.org/?Pieter%20Vander%20Vennet - all those statistics can be found there)
