### ISSUE TITLE
Highlight the last selected element

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#195]
There are Themes like Tree or Bicycle parking that have a lot of nodes on the map.

When I click one after another I get lost which one I clicked last.
This is also an issue since the map needs to move when I click an object in the middle of the screen, so the selected object is not where I saw it last after I close the QA-window.

The app could help me with that by highlighting the last clicked element. For example:
- I am in the details window of a tree
- I close it
- Now the previous selected tree "glows" up for 2 seconds and gets back to default afterwards

This would tell me "this tree was just edited" and allow me to select a different one.

This is also related to https://github.com/pietervdvn/MapComplete/issues/193

**Comment by pietervdvn** [comment]
Yeah, this is indeed an issue, also related to #174 

I'm not entirely sure yet how to solve this, but I was thinking about the addition of a meta-tag "_selected" which would change if it is selected - then the theme can handle the actual styling.

Because the markers are HTML-markers, a shadow can be applied.

On the mobile version, I'm thinking about introducing a small-map component which shows the selected element (which is non-interactive)

I'm in the running for a few projects, if we have them this will be implemented then.

**Comment by pietervdvn** [comment]
By now, I have implemented a special 'minimap'-component. This would be a partial solution for this, especially on mobile: 
![image](https://user-images.githubusercontent.com/1466478/123270577-5227fa00-d500-11eb-9a3a-3b637387cf81.png)
