### ISSUE TITLE
Images from Mapillary with tag Mapillary are not shown as a picture

### ISSUE THREAD

**Issue by StijnClaes** [pietervdvn/MapComplete#203]
For defibrillators (AED) very often a Mapillary tag is added to the object.
MapComplete seems to be configured to show this image at the top op the pop-up, but there seems to be a problem in the visualization of this image in the pop-up.
Example: https://mapcomplete.braindeaddev.com/aed.html?z=16&lat=51.19329&lon=4.735686&tab=4#node_7086906284

**Comment by pietervdvn** [comment]
Hi Stijn,

The instance on braindeaddev is hosted by someone very concerned with privacy. They blocked access to most third party websites, including mapillary as not to leak data (because mapillary is now owned by Facebook).

While I'm quite privacy-concerned too, I'm more of a pragmatist and don't do extensive third-party blocking on the official instance. As such, the mapillary images on the real instance work fine: https://mapcomplete.osm.be/aed.html?z=16&lat=51.19468&lon=4.736351&tab=4#node_7086906284
