### ISSUE TITLE
Make a glutenfree theme

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#2031]
So it's easy for people who are looking for places with glutenfree food to have one central theme to find them.

https://mas.to/@AccurstDemon/112807407944214886

**Comment by pietervdvn** [comment]
Already possible - there is a filter function for "glutenfree" in both shops and food; so there is no need to create a separate theme for this.

@HectorVda Yes, this is an excellent theme for quickly mapping. However, a regular user will also want to see opening hours and some other information; so having all the questions will probably work better. Note that, in settings, you can set that _all_ questions are shown at once instead of question by question which makes quickly adding a specific question easier. Also see #256

**Comment by pietervdvn** [comment]
>  to counter the people who don't find mapcomplete 

Hmm, that is true though...

**Comment by pietervdvn** [comment]
Done!
