### ISSUE TITLE
crossing=uncontrolled

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#2086]
If you choose
![image](https://github.com/user-attachments/assets/ad9032d4-c25e-4c21-a3a4-0d18853dbc68)
on a footway then it automatically assumes that there it's not a zebra crossing. why?

I don't select the 'Crossing without crossing markings' on purpose, because it does indeed have markings.

cc @RobinLinde

**Comment by RobinLinde** [comment]
This is because the layer assumes a zebra is tagged with `crossing_ref=zebra` and doesn't really have a good value for a crossing not being a zebra, so an empty `crossing_ref` assumes the crossing is not a zebra. I'm working on replacing the zebra question with a question for `crossing:markings` instead.

**Comment by RobinLinde** [comment]
Added a first version in https://github.com/pietervdvn/MapComplete/commit/ce744128910dc9e2302aa8ec877aeb06a7af1a60, demo (without images) is available [here](https://dev.mapcomplete.org/theme.html?userlayout=https://studio.mapcomplete.org/5093765/layers/crossings/crossings.json)
