### ISSUE TITLE
deleted photos aren't deleted

### ISSUE THREAD

**Issue by Marc-marc-marc** [pietervdvn/MapComplete#2146]
if you delete an image in MapComplete (by the sane account/session that add the photo), it is not deleted, only the tag is deleted
photos are still on https://imgur.com/ and available via the history

**Comment by thibaultmol** [comment]
This is a limitation of the current implementation. I don't think much can be done about this atm.
Anything uploaded to imgur is uploaded and can't be deleted (because it's done anonymously)

(Unless pieter responds differently. I don't think he'll put in the effort to fix this because over time it'll be changed to Panoramax for uploading anyway)
https://github.com/pietervdvn/MapComplete/issues/1451

**Comment by Marc-marc-marc** [comment]
2 ideas to solve this:
- don't send it immediately, so that you can delete a photo (for the moment, if you "take a photo", you can't leave without having taken a photo)
- allow you to upload with your name/login

**Comment by thibaultmol** [comment]
>  you can't leave without having taken a photo)

You should be able to just press the back button in android or do a swipe gesture on the gesture. I can get out of that menu without taking a picture

**Comment by pietervdvn** [comment]
As @thibaultmol says, this is currently not planned. Also, when someone uploads a photo, another user might use this photo and link it to a different feature. If the original uploader then deletes the picture, we'd have a dead link.

**Comment by thibaultmol** [comment]
Also good to know if you have accidentally uploaded an image that you
really want to be deleted (because it contains personal information or
something). You can request deletion as well
https://imgur.com/removalrequest
