### ISSUE TITLE
query via PlantNet add species:wikidata (no so usefull) and no species

### ISSUE THREAD

**Issue by Marc-marc-marc** [pietervdvn/MapComplete#2149]
the answer from PlanetNet is saved as species:wikidata
at least, species is more usefull (both is also an option)

**Comment by pietervdvn** [comment]
I'm deliberately using 'species:wikidata' because it sidesteps a whole lot of issues:

- Species is often used to write a name in the local language
- Species is often used to write a taxon, genus or other level (for which I don't know the difference)
- It is sometimes used with and without abbreviations
- The genus is sometimes renamed or changed taxon, or it is discovered that two genusses are actually the same
 
As such, I'm offloading this complexity to wikidata - even though I understand it makes filtering with overpass harder.

(Furthermore, I can show a pretty picture and information from Wikidata)
