### ISSUE TITLE
currently MC put source on object (old fashion), instead on the changeset

### ISSUE THREAD

**Issue by Marc-marc-marc** [pietervdvn/MapComplete#2150]
adding a species, objet get source:species:wikidata=PlantNet.org AI, in stead of a changeset tag

**Comment by pietervdvn** [comment]
No. Where some data was fetched from is not a property of the tree itself.

This will also give rise to many data issues. Consider the following scenario:

- Person A adds tree with MC, adds `species:wikidata` and `source:species:wikidata=plantnet`
- Person B edits this later on with e.g. iD and changes the species. Person B does not notice the source tag and forgets to remove it or update it.

Now we have an incorrect source tag.

Or what if a person changes the genus after determining it with plantnet? Should mapcomplete remove this source tag automatically?

As such, it is set into the changeset (because this is valid metadata).

Yes, I understand that you want to query for trees which have a species from/not from plantnet, but slapping this tag onto every tree is not the right way to do it. The correct way to do this is to download all trees (e.g. from overpass) and then to have a program to download the history for each object.
