### ISSUE TITLE
Remove not:tourism:artwork

### ISSUE THREAD

**Issue by mwild500** [pietervdvn/MapComplete#2196]
Please remove not:tourism:artwork tag that isn't in use.
It should be inserted only if answerd yes. In case of no there should be no tag or information.

"bench-artwork
The question is Does this drinking water fountain have an artistic element?

This drinking water point has an integrated artwork is shown if with [tourism](https://wiki.openstreetmap.org/wiki/Key:tourism)=[artwork](https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dartwork)
This drinking water point does not have an integrated artwork is shown if with [not:tourism:artwork](https://wiki.openstreetmap.org/wiki/Key:not:tourism:artwork)=[yes](https://wiki.openstreetmap.org/wiki/Tag:not:tourism:artwork%3Dyes)
This drinking water point probably doesn't have an integrated artwork is shown if with tourism=. This option cannot be chosen as answer"

**Comment by pietervdvn** [comment]
The `not`-prefix is a widely accepted practice: https://wiki.openstreetmap.org/wiki/Key:not:*

This is only set if a contributor explicitly answeres this question, this is IMHO valuable information too. Otherwise, we risk that people answer the same question over and over if we don't explicitly mark a 'not'-case.
