### ISSUE TITLE
Show the literal key/value being set

### ISSUE THREAD

**Issue by bryceco** [pietervdvn/MapComplete#222]
I was trying to add information to a playground using my native English language, and it asked about the surface and gave me a few choices in English. Great!

Next it asked me a series of questions in Dutch which I don't read well so I had to give up. If the question/answers subtly showed the OSM key:values (access:public) as well then I could have proceeded. 

Now I realize that you want to keep the app newbie friendly, so maybe this is something that gets enabled after a certain number of changesets or something.  But adding this clue is also helpful as an onboarding tool for new users to introduce them to the key:value system used by OSM, which they'll eventually need to know as they engage with the project more.

**Comment by pietervdvn** [comment]
Thanks for the feedback!

> Now I realize that you want to keep the app newbie friendly, so maybe this is something that gets enabled after a certain number of changesets or something

That is correct - once the user has 100 changesets, the tags are visible. However, that is a bit to much, especially because only a single changeset per hour is issued. I'll drop it to 20, and links to the wiki page appear at 30 changesets now.

> Now I realize that you want to keep the app newbie friendly, so maybe this is something that gets enabled after a certain number of changesets or something

I really should set up a decent translation service. And I should finish translating the theme ;)

**Comment by bryceco** [comment]
I have 2800 changesets and I don't see tags except on the page where I'm creating a new object.

**Comment by pietervdvn** [comment]
It is underneath the 'skip question'-button, but you have to select an answer first. Is there a location that would be more appropriate to place the tags?

![image](https://user-images.githubusercontent.com/1466478/111361979-95b3d200-868e-11eb-9e4c-4c0ec880ca53.png)

**Comment by bryceco** [comment]
I see, I was expecting to see "(access=public)" next to each answer. Alternatively could you have it display "key=" like you do now prior to a selection being made?

**Comment by pietervdvn** [comment]
That is pretty hard, as some options might trigger multiple tags. And to put it very bluntly, you (as experienced mapper) are not the target audience of this website. MapComplete is built to be usable by non-tech-savy people, whom will only be scared by to much of such 'computer lingo' they don't understand. It should be usable by your grandma too ;)

I definitively want to give the new contributor a push in the right direction to learn more - which is why the tags are there in the first place - but it shouldn't scare away the contributor that doesn't want/doesn't have the knowledge to learn more; so it has to be relatively small and subtle. Putting the full tag next to each radio button _would_ be to much IMHO.

**Comment by bryceco** [comment]
Okay I understand. I'd still like to have the key displayed before making a selection. For example: ![image](https://user-images.githubusercontent.com/279734/111365070-44d0b900-864f-11eb-9585-d0f9b6783fc0.png)
