### ISSUE TITLE
Add escalators to blind infrastructure theme

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#2247]
Escalators are tagged as stairs with a conveying tag
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dsteps#Escalator
currently mapcomplete doesn't look at the conveying tag.

so https://www.openstreetmap.org/way/961588202

looks like: https://mapcomplete.org/blind_osm.html?z=19.6&lat=51.10758433929152&lon=3.9864539141535715#way/961588202

it would be nice to have escalators properly shown (and maybe also direction?)

**Comment by RobinLinde** [comment]
Technically they were already somewhat visible, but only with `conveying=yes` and it only changed the title. When dev is deployed it'll also support `forward`, `backward` and `reversible`, with arrows, a different color and a question (which doesn't allow picking `forward`/`backward`, because I'm not sure whether there is a good way of showing/asking that.
