### ISSUE TITLE
Errormessage : "...input without freeform key..."

### ISSUE THREAD

**Issue by pelderson** [pietervdvn/MapComplete#227]
Both my themes now complain about a "tagrendering taking input without freeform key".  I did not change these themes, they worked when I put them on the MapComplete wiki. I am sure about that because I usually use the themes by starting them from the wiki list.

**Comment by pietervdvn** [comment]
I have added some extra checks on the themes in order to check for common mistakes. I've fixed up your Wandelknooppunten-theme on the wiki.

The error in this case was your 'this rwn_ref doesn't exist anymore'. I've changed the `render` field into an extra mapping which is triggered when `disused:rwn_ref` is _not_ set (thus always by default), giving more or less the same result.
