### ISSUE TITLE
Allow enabling/disabling questions

### ISSUE THREAD

**Issue by matkoniecz** [pietervdvn/MapComplete#256]
For example for me

> What is the email address of Cyclo-Centrum?

is something that I consider as not worth surveying so it spams Cyclofix in my area.

**Comment by pietervdvn** [comment]
I understand the concern... I'm gonna think about it.

**Comment by pelderson** [comment]
I support this issue. Currently, Skip is the most used option in my themes. I leave questions out of the theme because of that, while I would rather have the user decide to skip it until further notice. PS. I think 'edit anyway' and ' re-enable' should be possible, so maybe the tagrendering should appear, just with an explicit edit button (pen icon) and a re-enable button.
