### ISSUE TITLE
Open Toilet Map - also include 'free toilets' part of horeca

### ISSUE THREAD

**Issue by Thierry1030** [pietervdvn/MapComplete#561]
I added extra info about the toilets of this pub (https://www.openstreetmap.org/node/8914556543) in reference to this article: https://www.bruzz.be/samenleving/al-24-gratis-horecatoiletten-brussel-2021-11-02

I think it is useful to show these free toilets that make part of hotels, restaurants and bars in the toilet MC-theme ...

**Comment by RobinLinde** [comment]
I have a mostly working version in the `toilets-at-amenity` branch, which should be deployed in a few minutes at https://pietervdvn.github.io/mc/toilets-at-amenity/toilets.html?z=19&lat=50.84747&lon=4.352431&language=en#node/8914556543

**Comment by Thierry1030** [comment]
Hello @RobinLinde this is great news! I checked it in the meantime and it works fine! Thanks for that!

I still have a question: is it still an option to include/mention that the toilet makes part of an amenity?

In this example https://www.openstreetmap.org/node/8914556543 it's in Mapcomplete NOT CLEAR that you actually need "to go in the bar" to access the toilet ...

![image](https://user-images.githubusercontent.com/64559939/141693054-44735e1b-2aad-49ea-8ac7-7b2d8b0623a9.png)

**Comment by RobinLinde** [comment]
Should show like this in a few minutes (or a bit more):
![MapComplete](https://user-images.githubusercontent.com/1395345/141699421-f23925dd-be36-4598-aadd-6ca5e6fdc79c.png)

Took way too much time to figure out i typed `mapppings` instead of `mappings`...

Only things I can see that need to be fixed are deletion and maybe names for items with `amenity=toilets`

**Comment by Thierry1030** [comment]
Works perfect! Thanks again!

https://pietervdvn.github.io/mc/toilets-at-amenity/toilets.html?z=17&lat=50.83837&lon=4.345597&language=nl#node/9252535197

![image](https://user-images.githubusercontent.com/64559939/141751202-1c8cde39-07bf-4157-af0d-d8661a66256b.png)

**Comment by pietervdvn** [comment]
@RobinLinde Since I dumped ~1gigabyte (400k little files) of addresses onto the deploy repo (pietervdvn.github.io), the deploy will fail every now and then.


I'm also thinking about creating a way to make reuse of tagRenderings easy and feasible, so that one can import all the questions of one layer as (namespaced) renderings in another feature, so that one can import all 'toilet'-related stuff e.g. in the restaurants theme... 

But in the end, at what point should we start to do indoor mapping instead. To be continued/to be discussed when I have a bit more time.

**Comment by pietervdvn** [comment]
Related to #474

**Comment by RobinLinde** [comment]
Since it's now 2022, [here](https://mapcomplete-git-feature-toilet-at-amenity-robinlinde.vercel.app/toilets.html?z=19&lat=50.84747&lon=4.352431&language=en#node/8914556543)'s a reworked version, as a separate layer, reusing some of the tagrenderings of the toilet layer, and adding iconbadges and a description.
