### ISSUE TITLE
Open Etymology Map wrongly insert wikidata items under the the wikidata tag

### ISSUE THREAD

**Issue by musuruan** [pietervdvn/MapComplete#562]
It seems that after Nov 10th, Open Etymology Map wrongly inserts wikidata items under the the wikidata tag, which should contains the ID of the Wikidata item for the feature itself and not the Wikidata item for the feature's namesake.

[Some examples](https://osmcha.org/changesets/113787479?filters=%7B%22date__gte%22%3A%5B%7B%22label%22%3A%222021-10-15%22%2C%22value%22%3A%222021-10-15%22%7D%5D%2C%22editor%22%3A%5B%7B%22label%22%3A%22mapcomplete%22%2C%22value%22%3A%22mapcomplete%22%7D%5D%2C%22comment%22%3A%5B%7B%22label%22%3A%22%23etymology%22%2C%22value%22%3A%22%23etymology%22%7D%5D%7D), using OSMCha.

Wikidata item for the feature's namesake should be filled under name:etymology:wikidata. Please see: https://wiki.openstreetmap.org/wiki/Key:name:etymology:wikidata

Is there a UI bug?

![immagine](https://user-images.githubusercontent.com/1221995/141754059-9c541307-45df-4f70-bf9c-f28d0143f84e.png)
![immagine](https://user-images.githubusercontent.com/1221995/141754115-1470c0d5-58ed-4eae-8371-22fc5afa0187.png)

**Comment by pietervdvn** [comment]
Yes, this is definitively a UI-bug. The questions-box didn't render accidentally. The Wikipedia-article is shown to help people if information exists in Wikipedia (which was very helpful for me in Bruges). However, as the questions are missing, people thought that they had to use the wikipedia-box instead.

I've rolled out a new version where the questions are back and the wikipedia article _cannot_ be edited anymore, so that this cannot happen anymore.

So, the only thing resting is to clean up the made mess made - luckily only 9 changesets made it before your eye caught this bug.

**Comment by pietervdvn** [comment]
All changesets have been reviewed and corrected

**Comment by musuruan** [comment]
Thank you very much for fixing this issue and for cleaning up incorrect changes.

**Comment by pietervdvn** [comment]
Well, this was quite a big issue, so...
