### ISSUE TITLE
Make "Add new item" interface single step to trigger menu or hint better

### ISSUE THREAD

**Issue by matkoniecz** [pietervdvn/MapComplete#598]
Right now it is

- long press till "Add new item" with icon appears
- click on that icon/label

Maybe the "Add new item" interface can appear after just long press? Or change label to "Click here to add a new item"?

Right now it is confusing a bit - I long pressed and waited for menu to appear then tried again with ad block disabled.

(triggered by https://github.com/streetcomplete/StreetComplete/pull/3616#issuecomment-1003994872 ) for https://mapcomplete.osm.be/hailhydrant.html?z=17&lat=53.56607&lon=10.00143&language=en#welcome

**Comment by pietervdvn** [comment]
Hi,

Thanks for reaching out!

A short tap should trigger the 'add new item' pin just as well.

The extra tap to open the 'add new thing'-menu is very important:

- A new user might miss the context that long pressing will add something new
- Tapping or long pressing shouldn't suddenly hide the map, that is confusing as well
- In order to prevent accuracy errors and to show similar items, the user must be zoomed in to zoom level >19. Tapping the map will show the 'add new item' marker; tapping it again will then zoom to that marker, and only then the menu can be triggered.
- One could play a bit with the exact wording - you can do this in [the translation program](https://hosted.weblate.org/translate/mapcomplete/core/en/?offset=1&q=state%3A%3E%3Dtranslated+add+new+item&sort_by=-priority%2Cposition&checksum=). I pull in the updates for those frequently.

So, while it might be a bit confusing at first, I'm afraid that immediately opening the 'add new item'-menu will be even more confusing and will be very annoying.

The other option is to have a button somewhere to add a new item (typically in the bottom-right, pioneered by Material Design for Android). This however only works on Android, can be confused with 'zoom in' and requires that users drag the map to the right location in any case.

If you see another, better solution - let me know; but I'm afraid that

**Comment by matkoniecz** [comment]
I changed label at https://hosted.weblate.org/translate/mapcomplete/core/en/?offset=1&q=state%3A%3E%3Dtranslated+add+new+item&sort_by=-priority%2Cposition&checksum= to "Click here to add a new item" with hope that it will be more clear - but feel free to revert

**Comment by pietervdvn** [comment]
Allright! When the translation updates hit, it'll be deployed. We'll see how it is received by other users.

Thanks for helping!
