### ISSUE TITLE
Hard for experienced OSM editors to grasp MapComplete's tagging rules

### ISSUE THREAD

**Issue by gdt** [pietervdvn/MapComplete#603]
I'm an experienced mapper (closing in on 3k changesets), usually using josm, and just came across MapComplete.  I have used StreetComplete some, but 95% of my mapping has been josm.

My initial reaction was to use it not so much to edit, but as a thematic viewer so I could know what's missing, for things that don't tend to render, e.g. fire hydrants, and then I looked at "public bookcases".  I had added one but it doesn't show (but I see the book icon in carto standard).    So, I wanted to click something that would take me to a page that says what mapcomplete thinks the rules are, in terms of what is displayed for each theme.   E.g., what tags  define "public bookcase"?  In the US these are often called "Little Free Libraries, and many tag them sort of like libraries, but indeed using "public bookcase" as a description is useful as they are unlike real libraries.

As an experienced mapper I know how to go read the tagging wiki and maybe start an argument on tagging@.  As a nerd I know I can read your source code.    So I would like to see some link "for experts, what defines this feature in OSM".   I gather there is some "unlock" after N edits, but I'm looking at this from the view of the larger OSM community and my bias to edit in josm based on field data collection, and seeing this as a way to know what's missing.   So your view of what tags count is interesting, both because your app has users, and because surely you have thought about it.

**Comment by pietervdvn** [comment]
Hi,
- Can you link the public bookcase that is not appearing?
- Every theme is configured as JSON file. You can read the definition for public bookcases [here](https://github.com/pietervdvn/MapComplete/blob/develop/assets/layers/public_bookcase/public_bookcase.json). The JSON format is documented [here](https://github.com/pietervdvn/MapComplete/blob/develop/Docs/Making_Your_Own_Theme.md)
- Tagging a public bookcases as 'amenity=library', 'description=public bookcase' is very wrong and is not supported by OSM. The correct tagging is `amenity=public_bookcase` as is [documented on the wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpublic_bookcase)

Also: @tordans points out that this is indeed visible in the 'add new item'-menu; as you have over 30 changesets you should be able to see them as well.

I'm not really sure what your underlying issue is - so I'm closing this now.

**Comment by gdt** [comment]
The one that didn't show up was amenity=library.   I just fixed it.    I probably added it before the amenity=public_bookcase tagging proposal happened.  There is of course data in osm not caught up to the latest tagging rules.

I did not log in, because I didn't want to use this app to add.   I am just trying to use it to browse, and I wanted to know what hte rules were for reading the db and what's displayed as a bookcase, not what the writing rules were (probably they are the same).  For me, clicking add, just tells me I need to log in.  It's not that I distrust, you, but I follow the Principle of Least Privilege, so I didn't log in.

Anyway, I checked out the sources and it was easy to find, and to figure out without the json docs- but thanks for the pointers.

I  am merely suggesting in the main "about" screen  something like

This map displays public bookcases, which on openstreetmap are denoted as <a href="tagging page">amenity=public_bookcase</a>.   And, if you are using an interpretation other than exactly what the wiki says, say that.

but I realize this is something you think could be offputting to newbies, and at odds with your gamification notion.  I just thought a different perspective might be useful.
