### ISSUE TITLE
Support bing maps

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#648]
Seems like bing needs to do special...

- [x] Request an API key (readers of the issue tracker: feel free to request one for me)
- [x] Doublecheck that a user must be logged in before this layer is available (readers of the issue tracker: if you find precise documentation, feel free to share) 
- [x] Implement the URL-fetching
- [x] Add to list

**Comment by pietervdvn** [comment]
Also see https://github.com/osmlab/editor-layer-index/issues/1441 and https://wiki.openstreetmap.org/wiki/Bing_Maps

**Comment by pietervdvn** [comment]
A lot of work for little benefit and a potential privacy nightmare

**Comment by tordans** [comment]
> A lot of work …

I just finished adding BING aerial imagery to the Zlant parking lane tool with https://github.com/zlant/parking-lanes/pull/159

That was quite painful due to Leaflet and the fact that Bing uses this quadKey URL pattern …

However, I assume it should be a lot easier to add to Maplibre GL JS.

> … little benefit …

I think that changed with the removal of this other global image pro that happened recently. In some areas Bing is the only viable imagery source.

> … and a potential privacy nightmare

I don't think that is true. At least not more or less than with any other image source that ELI provides. My understanding from a privacy point of view for a map application arial imagery is a core feature and as such can be expected to be part of the app. Also the users actively choose to show the given layer (in most cases (not when following a pre defined URL)), so there is some opt in.

The Zlant editor is not ideal in that regard, because it creates the first request when the app is initialized. But I consider that OK for this specific app.

**Comment by pietervdvn** [comment]
You make some interesting points there. Would you willing to create an API key from Bing for MapComplete (or can we reuse the ZLant one)? 

Would you be up to implementing this in MapComplete?

**Comment by pietervdvn** [comment]
> That was quite painful due to Leaflet and the fact that Bing uses this quadKey URL pattern …

> However, I assume it should be a lot easier to add to Maplibre GL JS.

Correct, this is apparently already implemented: https://github.com/maplibre/maplibre-gl-js/discussions/2350
