### ISSUE TITLE
iFrame layout

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#654]
When using an iFrame, it seems to be impossible to have BOTH a button to open a full screen version (3)  AND the welcome message. Even when you close the welcome message, the button does not appear.
The double scrollbar on the right is also a little annoying

![afbeelding](https://user-images.githubusercontent.com/10122639/153621083-33d36c1b-92da-4c5c-b0dd-b1a0b4a9fe19.png)

**Comment by pietervdvn** [comment]
1) The double scrollbar has been fixed
2) If the iframe is 768 pixels or wider, then the popups are used. If smaller, the fullscreen behaviour is toggled.
3) The 'iframe-popout'-button is by definition incompatible with the welcomeMessage, it appears by definition only if the welcomemessage is disabled.

**Comment by pietervdvn** [comment]
I have made the 'iframePopout' a generic link which can be set by the theme and can be configured to show in iframe mode/welcome message hidden mode.

This should also mean that an application such as waldbrand-app (by @sebkur ) can simply define the 'go back to the website'-button from the theme layout instead of doing a custom hack.
