### ISSUE TITLE
Add a question: "I reviewed the existence of this place"

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#68]
Why?

    this allows us to drop POIs from "priory lists", even if the user didn't have to edit anything else
    it allows to assess data quality!

Data model:
Question: Does this object still exist?
If yes, fill in check_date:existence with the current date (optional)
If no, add lifecycle prefix to main tag and a fixme="this object can probably be deleted"

(migrated from https://github.com/osmbe/cyclofix-docs/issues/13)

**Comment by westnordost** [comment]
Isn't `check_date` for the existance already?

**Comment by westnordost** [comment]
FYI StreetComplete uses `check_date` now to mark the existence of an object.

**Comment by pietervdvn** [comment]
Ah, cool, I'mma check it out

**Comment by westnordost** [comment]
Since [v28.0]( https://github.com/streetcomplete/StreetComplete/releases/tag/v28.0)

Code for that particular quest is here: https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/existence/CheckExistence.kt

**Comment by pietervdvn** [comment]
Cool reference, also cool to to see you offloading all the 'hard work' onto overpass ;)

If this is ever added, my implementation will be simpler, due to the goal of the applications: Streetcomplete has the attitude of "OpenStreetMap is cool - which questions can be answered nearby", whereas the idea of MapComplete is "Here is a map of what is interesting for XYZ-topic - help out answering questions! (Oh, btw, do you know about OpenStreetMap)?"

This would permit me to always show the question "does it still exist" on every shown element, but I might restrict the question to only show up if the geolocation is sufficiently closeby...

Anyway, this is a low priority for now anyway, but I wanted to record these thoughts.

**Comment by westnordost** [comment]
> Cool reference, also cool to to see you offloading all the 'hard work' onto overpass ;)

The app does not use overpass anymore.

**Comment by pietervdvn** [comment]
Woo, that is cool! So you are using the OSM-API directly?
Do you download _all_ the elements in view then? Is it able to handle an entire city, e.g. Brussels?

**Comment by westnordost** [comment]
Yes, directly from the OSM API. All the elements in a view. Theoretically it is possible to handle an entire city because it bypasses the OSM API restriction of that the download size may be at most X MB (by splitting up one request into several recursively), however there is a client-side restriction in place which only allows the user to download a certain maximum area.

**Comment by pietervdvn** [comment]
This can now be implemented by the theme itself, by using a mapping as `survey:date:={_now:date}` - a combination of [Calculated Tags](https://github.com/pietervdvn/MapComplete/blob/master/Docs/CalculatedTags.md) and the new tag checking `:=`
