### ISSUE TITLE
Property `enableImproveAccuraccy` is not allowed.

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#789]
The validator shows this warning for nearly all themes.

> Property enableImproveAccuraccy is not allowed.

```
      "allowMove": {
        "enableRelocation": false,
        "enableImproveAccuraccy": true
      },
```

I don't know if this is a missing key in the schema or if the key should be removed from all themes (and the schema is right…).

**Comment by tordans** [comment]
I cannot find the string `enableImproveAccuraccy` in the codebase, so likely the schema is right and the theme files should be updated.

I wonder, is there a Github action in place that validates the themes against the schema from time to time?

**Comment by pietervdvn** [comment]
Hmmm, they are [here](https://github.com/pietervdvn/MapComplete/blob/84284599d8b66beb5aa75998e89faa8e127a2ff6/Models/ThemeConfig/Json/MoveConfigJson.ts#L6) and [here](https://github.com/pietervdvn/MapComplete/blob/84284599d8b66beb5aa75998e89faa8e127a2ff6/Models/ThemeConfig/MoveConfig.ts#L5)

It is used here: https://github.com/pietervdvn/MapComplete/blob/1271f241603918db41a37c61f4222f9de8896c18/UI/Popup/MoveWizard.ts#L68

There is a script to update the scheme files though, is seems like it has been a while since I last ran it: `npm run generate:schemas`

**Comment by pietervdvn** [comment]
This being cleared, it might be a good idea to validate these schema files in the build script too, so that they are updated regularly.

Validating the theme and layer files against these schemas would be nice too. Is there a command line tool which does this?
