### ISSUE TITLE
Add `survey:date` based on capture date of imagery, if imagery added

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#879]
While I understand it would probably be a bad idea to start adding survey dates to all things added to mapcomplete purely on the basis of 'it was added or modified recently', it might useful to add a date that corresponds to a streetview imagery date. (and if in the future a newer streetview imagery is chosen, update the survey date)

Pic4review also does this (when you add objects based on Mapillary detections to osm)

**Comment by pietervdvn** [comment]
Hi,

I don't think that this is wanted behaviour.

- Some themes do have a question to explicitly set the survey date. Selecting a mapillary image afterwards would override this date (to an older date)
- The goal of MapComplete is (partly) to edit on the go. Combined with the distances to the edited objects in the changeset metadata, one can try to verify whether or not it was truly surveyed
- Data consumers can do the exercise of fetching the survey date themselves; this data can be calculated

**Comment by thibaultmol** [comment]
Sorry, what I meant to say was `check_date`
https://wiki.openstreetmap.org/wiki/Key:check_date
Similar to Streetcomplete. It just verifies the last date the object has been seen.

I think this could be really beneficial for keeping osm up to date (and verifying that)

**Comment by pietervdvn** [comment]
If you are gonna add such a property automatically based on the mapillary-metadata, it can still be automatically calculated afterwards - so no use to add it in.

**Comment by thibaultmol** [comment]
True but not easily. You can't do that using Overpass for example. While if the items have check_date (like how Streetcomplete adds it) then you can easily query which items haven't been checked lately

**Comment by pietervdvn** [comment]
> MapComplete could suggest to update survey:date if picture's date is newer 😃
The user could answer "yes" or type a new date.

Which boils down to having the 'surveyed today' question, but now only in some cases

> It could be difficult for "simple consumers to fetch the date from Mapillary, Panoramax… and futures image providers.
MapComplete could do this once when the picture is selecte

Data consumers would still have to do this excercise. MapComplete isn't widely used and linking images is pretty rare. There are 368K mapillary-tags on OSM, only a few hundred (or maybe thousand) were linked with mapcomplete

At last, adding tags for a specific, certain data consumer is not my end goal nor responsability and sounds suspiciously like 'tagging for the renderer'. Even worse is that this is about hypothetical data consumers!

I'm personally also quite opinionated against the 'survey'-tag - when someone last looked to an object is _not_ an inherit property of said object and not verifiable for someone else. The lasr-surveyed question was added only after a lot of nagging.

So, this issue is a hard no.

> Personnaly I used MapComplete from my desktop

Sure, if this works for you!

**Comment by pyrog** [comment]
> I'm personally also quite opinionated against the 'survey'-tag - when someone last looked to an object is _not_ an inherit property of said object and not verifiable for someone else.

The `survey:date` is verifiable by anyone: this is the date of the picture 😎 
By memory, in [Every Door](https://github.com/Zverik/every_door) you could set preference to choose `survey:date`,`check_date` or noting.



> At last, adding tags for a specific, certain data consumer is not my end goal nor responsability and sounds suspiciously like 'tagging for the renderer'.

This is an **help** for contributors who want to update this tag, especially beginners 😃 
(MapComplete currently fetch and display the picture's date, so it's seem easy to keep it and suggest it to the user).

> Personnaly I used MapComplete from my desktop

But I will try sooner to use it on the field with may small phone 😅
