### ISSUE TITLE
Offer picture suggestions

### ISSUE THREAD

**Issue by pbb72** [pietervdvn/MapComplete#89]
There are several resources of geotagged, public domain/CC photos available online. Examples are WikiMedia/Wikipedia, Flickr, Mapillary, OpenStreetCam.

When editing a feature, automatically load nearby photos from these resources, and allow the editor to choose one of these. (Instead of having to go out, make the photo yourself, and upload that.)

**Comment by pietervdvn** [comment]
Hey,

This is a great idea. However, at the moment I do not have the spare time available to implement all these integrations.
One that is pretty high on my list is integration with wikipedia/wikimedia though, in order to link a wikipedia article with an OSM-object easily. This is however for when I have some time for it...

**Comment by RobincYoung** [comment]
[Pic4Carto.js](https://framagit.org/Pic4Carto/Pic4Carto.js) can fetch geotagged photos from  WikiMedia, Flickr, Mapillary and OpenStreetCam.

**Comment by pietervdvn** [comment]
Hi @RobincYoung - that library is precisely what I needed.

MapComplete now can show nearby images, this is momentarily live on pietervdvn.github.io/mc/develop and will make it's way to prod eventually.
