### ISSUE TITLE
cyclestreets vs. bicycle roads

### ISSUE THREAD

**Issue by Discostu36** [pietervdvn/MapComplete#986]
The cyclestreets theme uses the word "Fahrradstraße" in the German translation. German Fahrradstraßen are tagged with `bicycle_road`, not with `cyclestreet`. The theme should not be shown in the German version of the website or should use the bicylce_road tag when edits are made in Germany.

**Comment by pietervdvn** [comment]
Hi,

Is there a concept in Germany where a street is mixed traffic (thus: both cyclists and cars can drive there) but cars are not allowed to overtake cyclists? What would be the word for this?

**Comment by Discostu36** [comment]
Bicycle roads (Fahrradstraßen) in Germany generally don't allow cars, but it is possible to allow cars there with an additional sign. Cars are then allowed to overtake cyclists if they can keep at least 1.5 meters distance from the cyclists while doing so (but that rule also applies on normal streets).

There is a new sign in Germany with the meaning "overtaking cyclists not allowed" but it is only used in cases where it would also not be allowed without the sign, so only to make car drivers aware that the 1.5 meter rule applies there.

**Comment by tordans** [comment]
My understanding is, that the tags mean nearly the same but are only used in their corresponding country. This is the way I read the short section of the wiki https://wiki.openstreetmap.org/wiki/Key:cyclestreet#Germany as well. 

To me this looks like a historic artefact of tagging that does not make a lot of sense in hindsight.

**Comment by RobinLinde** [comment]
Just to make it a bit more complicated, some municipalities in NL are using signs similar to the German signs (https://commons.wikimedia.org/wiki/File:Fietsstraat_Delft.jpg)
Which implies some of the same rules as `bicycle_road` (e.g. no cars allowed if not explicitly signed), but there are also streets that look more like a `cyclestreet` and use the sign as used in Belgium. TL;DR: NL has no regulations, some municipalities dream up their own signs.

I think the a solution might be to let the layer show streets tagged as `bicycle_road=yes` as well as `cyclestreet=yes`, add a mapping for `bicycle_road=yes` only shown in Germany so that's the tag being used when adding a new street. Would probably also be nice to split out the layers and add a question about the specific sign and additional signs.

**Comment by RobinLinde** [comment]
My current tests are now live at https://pietervdvn.github.io/mc/feature/bicycle_road/cyclestreets.html. Mappings and traffic_sign done, don't think I'm gonna split out the layers just yet (questions are added using override, so just splitting out the layers wouldn't give very usable layers). I've also fixed the icon rendering and changed it to local signs for Germany and Finland.

**Comment by Discostu36** [comment]
![Screenshot_20220813-161212_1.png](https://user-images.githubusercontent.com/30999326/184498049-38820b14-ef47-434e-8d49-e075758d9c33.png)
This needs "none" as an option IMHO.

**Comment by Discostu36** [comment]
Something about the traffic sign tagging is faulty, choosing allowed for motor verhicles results in `1022-12;DE:244.1,1020-30,1024-10` as a value

**Comment by RobinLinde** [comment]
> Something about the traffic sign tagging is faulty, choosing allowed for motor verhicles results in `1022-12;DE:244.1,1020-30,1024-10` as a value

Probably an issue of me using Github Copilot, or not having enough sleep, will push a fix for that.

I've changed the answers to show the full sign, as well as have a basic none option.
![image](https://user-images.githubusercontent.com/1395345/184508226-2ea70e01-4c68-43dd-93a1-58c8154dc2eb.png)


Also changed the icon to render based on the `traffic_sign` value.
![image](https://user-images.githubusercontent.com/1395345/184508184-a4b46feb-795c-468a-ba06-eb13de1ce951.png)

Currently still building, so should be live in less than an hour
