### ISSUE TITLE
Uploading images to Wikimedia Commons

### ISSUE THREAD

**Issue by pyrog** [pietervdvn/MapComplete#99]
**imgur** display advertising 😞 and **Wikimedia Commons** is well supported by others Osmose applications.

It will be useful to use it 😄

**Comment by pietervdvn** [comment]
I would love it as well.

 At first I attempted to upload directly to Wikimedia, but that was very hard to implement. I spent like a day trying to figure that out. A second (somewhat minor) issue is that a user then _also_ has to connect to their wikipedia, or a dedicated wikipedia acocunt should be setup.

I got Imgur working in like 15 minutes, so that was a very pragmatic choice. Note that I prepared a transfer from Imgur to Wikimedia by making sure all images have a compatible license and such.

If you have experience hooking up the Wikimedia API, I would love some help with this...

**Comment by pyrog** [comment]
> If you have experience hooking up the Wikimedia API, I would love some help with this...

Yes 😃 

> a user then also has to connect to their wikipedia

Seem that Wikimedia use [OpenID](https://www.mediawiki.org/wiki/Extension:OpenID_Connect)

**Comment by pietervdvn** [comment]
Oooohhh... 

My current two biggest questions are:

1. Would it be possible to assign enough metadata from the OSM-object in order to have enough for Wikimedia? A picture upload should be still one click to do.
2. Would it be possible to upload something without the user being logged in in Wikimedia as well? Thus an 'anonymous'-upload or an upload with a dedicated MapComplete account?

If the answer on both is yes, we can get this rolling!

The easiest would be if you could send some typescript code. Or, if you dare to, set up the project. 3rd party API code goes into `Logic/Web` (there even is some Wikimedia-specific code there already, but it might be easier to create a `WikimediaLogin.ts` module there). test.html and test.ts are testing classes, ideal to make some proof of concept.

I know they support OpenID and OAuth, but these are still a pain to set up (I used a package for OSM-login which made it a lot easier).


Once we have a decent upload, we can start thinking about allowing users to login with their own wikipedia account. This is mainly a user experience issue, but we'll figure something out.

**Comment by pyrog** [comment]
> If the answer on both is yes, we can get this rolling!

Yes (Osm Hydrant project do this).

But personally, I prefer to be credited as author 😉 so it's better to use OAuth or OpenId.

> I know they support OpenID and OAuth, but these are still a pain to set up 

Ok

**Comment by pyrog** [comment]
> I used a package for OSM-login which made it a lot easier

See https://github.com/osmlab/osm-auth/issues/69

**Comment by pietervdvn** [comment]
That would be great, but it seems that that library is not maintained anymore... Would be great though if it still was...

**Comment by pietervdvn** [comment]
Due to many difficulties (technical and social), I'm abandoning the idea of uploading images to Wikimedia commons.

However, I'll probably switch to Geovisio soon (see #1451 )

**Comment by opk12** [comment]
Just for posterity, Commons does not support generic street-level imagery. The [Project scope](https://commons.wikimedia.org/wiki/Commons:Project_scope) policy forbids content without educational value¹. A non-notable POI is required to have something unique, for example it documents a notable place or showcases an art movement. And the photo will be deleted when there's a "better alternative", which means anything from a higher resolution photo² to an alternative POI.

¹ Educational value is automatically assumed if the file is used in the article namespace (ns0) of Wikipedia and sister projects. The rest is evaluated case-by-case.
² An alternative with better light, resolution, ... is allowed to have a different file name, so the file name would not even work as an identifier in this case.
